### ISSUE TITLE
Automat - vytvorenie dátového súboru (json)

### ISSUE THREAD

**Issue by hutnikus** [hutnikus/automat#6]
Ukladanie momentálneho stavu do súboru

- [ ] json pre Rad #2 
- [ ] json pre Kasa #3 
- [ ] json pre Automat #1
